'use strict';
const BUILD='2026.09.29.SA2.1', KEY='kmt-notes-v1', DRAFT='kmt-draft-v1';
const main=document.getElementById('main'),dialog=document.getElementById('detail');
let items=[],live=false,readPending=null,sourceDate='',lastRead='',screen='home',filter='all',returnFocus=null,readMessage='현재 상태를 불러오는 중…',recognition=null,installPrompt=null;
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(s){return String(s||'').toLowerCase().replace(/[\s\-‐‑–—]/g,'');}
function heading(k,t,sub=''){return `<div class="sheet-head"><div><div class="eyebrow">${esc(k)}</div><h2>${esc(t)}</h2></div><button class="icon" aria-label="상세 닫기" onclick="dialog.close()">×</button></div><div class="sub">${esc(sub)}</div>`;}
function open(html){stopVoice();if(!dialog.open)returnFocus=document.activeElement;$('sheetBody').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
dialog.addEventListener('close',()=>{stopVoice();if(returnFocus?.isConnected)returnFocus.focus();});
function toast(text){clearTimeout(toast.timer);$('toast').hidden=true;let target=$('toast');if(dialog.open){target=$('dialogStatus');if(!target){target=document.createElement('p');target.id='dialogStatus';target.className='alert';target.setAttribute('role','status');$('sheetBody').appendChild(target);}}target.textContent=text;target.hidden=false;if(dialog.open)target.scrollIntoView({block:'nearest'});toast.timer=setTimeout(()=>target.hidden=true,4500);}
function readStore(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch{return fallback;}}
function persist(key,value){localStorage.setItem(key,JSON.stringify(value));if(localStorage.getItem(key)!==JSON.stringify(value))throw Error('storage_failed');}
function notes(){const a=readStore(KEY,[]);return Array.isArray(a)?a:[];}
function updateNote(id,patch){const a=notes(),r=a.find(r=>r.id===id);if(!r)throw Error('missing_note');Object.assign(r,patch);persist(KEY,a);return r;}
async function api(path,body,timeout=25000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(path,{credentials:'same-origin',cache:'no-store',signal:c.signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let d;try{d=await r.json();}catch{throw Error('invalid_response');}if(!r.ok||d.ok!==true){const e=Error(d.error||'request_failed');e.status=r.status;e.data=d;throw e;}return d;}finally{clearTimeout(timer);}}
function active(name){screen=name;document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('selected',b.dataset.page===name));}
function banner(){document.querySelector('.demo').innerHTML=`<b>수정 버전 ${BUILD}</b><span>${live?'연결됨 · ':''}${esc(readMessage)}</span>`;}
async function refresh(){if(readPending)return readPending;readMessage='현재 상태를 불러오는 중…';banner();readPending=(async()=>{try{const d=await api('/api/real-status');if(d.live!==true||!Array.isArray(d.currentStatus))throw Error('invalid_response');items=d.currentStatus.map((x,id)=>({...x,id}));live=true;sourceDate=d.sourceLatestDate||'';lastRead=new Date().toLocaleString('ko-KR');readMessage=(d.test?'검증 데이터 · 운영 아님 · ':'')+`${items.length}건 · ${sourceDate||'기준일 미등록'}`;return true;}catch(e){items=[];live=false;readMessage=e.status===401?'사용자 등록 · 연결이 필요합니다':'현재 상태를 불러오지 못했습니다. 다시 시도하세요.';return false;}finally{readPending=null;banner();if(screen==='home')home();if(screen==='work')work(filter,$('search')?.value||'');}})();return readPending;}
function card(x){return `<article class="item"><div class="item-top"><div class="item-status"><span class="tag">${esc(x.state)}</span><button class="schedule-button" onclick="scheduleReport(${x.id})">계획일정 ↗</button></div><span class="category">${esc(x.process)}</span></div><button class="item-detail" aria-label="${esc(x.customer)} ${esc(x.model)} 업무 상세" onclick="openItem(${x.id})"><h3>${esc(x.customer)}<small>${esc(x.model)}</small></h3><p class="issue">${esc(x.cause||'원인 미등록')}</p><div class="next"><span>${esc(x.nextAction||'다음 행동 확인 필요')}</span><span>›</span></div></button></article>`;}
function reports(){return `<section><div class="section-title"><h2>생산 · 지원 집계</h2></div><div class="report-links"><button onclick="productionReport('month')">▥ 월간생산량<small>집계 연결 확인 ›</small></button><button onclick="productionReport('year')">▤ 연간생산량<small>집계 연결 확인 ›</small></button><button onclick="supportReport()">⇄ 타부서지원<small>누적 집계표 ›</small></button></div></section>`;}
function home(){active('home');const urgent=items.filter(x=>x.priority===1).length,waiting=items.filter(x=>/대기|보류|지연/.test(x.state)).length;main.innerHTML=`<div class="date">${esc(new Date().toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'long'}))}<button class="chip" style="float:right" onclick="refresh()">새로고침</button></div><h1>오늘의 <span>생산 현황</span></h1><p class="lead">현재 상태와 다음 행동을 한눈에 확인하세요.</p><section class="brief"><div class="brief-label">✳ 그로우 · 현장 브리핑</div><h2>${live?`현재 관리 이슈 <em>${items.length}건</em>`:'현재 상태 연결을 확인하세요.'}</h2>${items.map(x=>`<button onclick="openItem(${x.id})"><span>${esc(x.customer)} · ${esc(x.model)}</span><strong>${esc(x.state)}</strong></button>`).join('')}${!live?'<button onclick="login()">앱 연결하기 ↗</button>':''}</section><div class="metrics"><button class="metric" onclick="work('waiting')"><small>대기·보류</small><strong>${live?waiting:'—'}<span>건</span></strong></button><button class="metric" onclick="work('urgent')"><small>우선순위 1</small><strong>${live?urgent:'—'}<span>건</span></strong></button><button class="metric" onclick="work()"><small>전체 이슈</small><strong>${live?items.length:'—'}<span>건</span></strong></button></div>${reports()}<div class="section-title"><h2>현재 관리 상세</h2><span>${live?items.length+'건':'연결 대기'}</span></div>${items.map(card).join('')}<p class="source">${live?`현재 상태 기준일 ${esc(sourceDate||'미등록')} · 조회 ${esc(lastRead)}`:esc(readMessage)}<br>담당·완료 여부는 원본 기록을 기준으로 확인합니다.</p>`;banner();}
function work(f='all',query=''){active('work');filter=f;main.innerHTML=`<h1>업무 <span>한눈에</span></h1><p class="lead">현재 관리 이슈를 검색합니다.</p><div class="search"><input id="search" aria-label="고객 또는 장비 검색" value="${esc(query)}" placeholder="고객명 · 장비명 · 상태" oninput="renderList()"></div><div class="tabs">${[['all','전체'],['waiting','대기·보류'],['urgent','우선순위 1']].map(([v,t])=>`<button class="chip ${f===v?'active':''}" onclick="work('${v}')">${t}</button>`).join('')}</div><div id="list"></div>`;renderList();}
function renderList(){const q=norm($('search').value),a=items.filter(x=>(filter!=='waiting'||/대기|보류|지연/.test(x.state))&&(filter!=='urgent'||x.priority===1)&&norm([x.customer,x.model,x.state,x.cause,x.orderId].join(' ')).includes(q));$('list').innerHTML=a.length?a.map(card).join(''):`<div class="empty">${live?'일치하는 업무가 없습니다.':esc(readMessage)}</div>`;}
function openItem(id){const x=items[id];if(!x)return toast('최신 상태를 다시 불러오세요.');open(heading(x.process,x.customer,x.model)+`<div class="action-box">현재 · ${esc(x.state)}</div><h4>상태 시작 · 지속</h4><p>${esc(x.since||'미등록')} · ${Number.isFinite(x.days)?x.days+'일째':'기간 미확인'}</p><h4>원인 / 이슈</h4><p>${esc(x.cause||'미등록')}</p><h4>다음 행동</h4><p>${esc(x.nextAction||'미등록')}</p><p class="note">${esc(x.issueId)} · ${esc(x.issueStatus)} · 원본 최신 ${esc(x.sourceLatestUpdate||sourceDate)}</p><button class="primary" onclick="input(${id})">이 업무에 진행 내용 입력</button><button class="secondary" onclick="scheduleReport(${id})">계획일정 확인</button>`);}
function unavailable(title,description){open(heading('연결 상태',title,'실제 데이터 연결이 필요합니다')+`<div class="alert">${esc(description)}</div><p>값을 0 또는 완료로 대신 표시하지 않습니다.</p><button class="secondary" onclick="dialog.close()">닫기</button>`);}
function productionReport(mode){unavailable(mode==='month'?'월간생산량':'연간생산량','현재 조회 서비스에 생산 완료일·완료 수량이 없어 실적을 집계할 수 없습니다.');}
function supportReport(){unavailable('타부서지원 누적 집계표','현재 조회 서비스에 지원 부서·지원 시간·기준일이 연결되지 않았습니다.');}
let planRequest=0;
async function scheduleReport(id){
 const x=items[id];if(!x)return;
 const request=++planRequest;
 open(heading('계획일정',x.customer,x.model)+'<p id="planResult">원본 계획을 불러오는 중…</p>');
 const result=$('planResult');
 if(!x.orderId){result.textContent='프로젝트 ID가 없어 계획을 안전하게 연결할 수 없습니다.';return;}
 try{
  const d=await api('/api/plans',{orderId:x.orderId});
  if(request!==planRequest||!result.isConnected||!dialog.open)return;
  if(d.orderId!==x.orderId||!Array.isArray(d.plans))throw Error('invalid_plans');
  result.outerHTML='<div class="alert">계획은 완료 실적이 아닙니다. 일정 수정은 개인계정 권한과 변경이력 연결 검증이 필요합니다.</div><p>'+esc(x.orderId)+'</p>'+
    (d.plans.length?d.plans.map(r=>'<article class="item"><b>'+esc(r[3])+' · '+esc(r[10])+'</b><p>'+esc(r[11]||'상태 미등록')+'</p></article>').join(''):'<p>이 프로젝트 ID에 연결된 계획이 없습니다.</p>');
 }catch{if(request===planRequest&&result.isConnected)result.textContent='계획을 불러오지 못했습니다. 연결을 확인한 뒤 다시 여세요.';}
}
function input(id){const x=typeof id==='object'?id:items[id],d=readStore(DRAFT,{}),target=x?`${x.orderId?x.orderId+' · ':''}${x.customer} · ${x.model}`:d.target||'';open(heading('FIELD NOTE','현장 입력','기기에 보관한 뒤 내용을 확인하여 서버로 보냅니다')+`<label>입력 대상<input id="inputTarget" aria-label="입력 대상" maxlength="160" value="${esc(target)}" placeholder="고객명 · 장비명" oninput="saveDraft()"></label><label>무엇이 달라졌나요?<textarea id="draft" aria-label="진행 내용" maxlength="800" placeholder="확인한 사실과 다음 행동을 입력하세요." oninput="saveDraft()">${esc(d.text||'')}</textarea></label><button class="chip" onclick="voice()">◉ 음성 입력</button><p id="inputHint" class="note">${d.text?'보관한 초안을 불러왔습니다.':'입력 원문은 이 기기에 보관됩니다.'}</p><button class="primary" onclick="saveNote()">처리함에 보관하고 확인</button><p class="note">사진 첨부·QR 스캔은 아직 연결되지 않았습니다. 사진이나 인식 결과가 저장된 것처럼 표시하지 않습니다.</p>`);}
function saveDraft(){try{persist(DRAFT,{target:$('inputTarget').value,text:$('draft').value});$('inputHint').textContent='이 기기에 초안 보관됨';}catch{$('inputHint').textContent='기기 저장에 실패했습니다. 화면을 닫기 전에 원문을 복사하세요.';}}
function saveNote(){const target=$('inputTarget').value.trim(),text=$('draft').value.trim();if(!target||!text){$('inputHint').textContent='입력 대상과 진행 내용을 모두 작성하세요.';return;}try{const id=crypto.randomUUID(),r={id,submissionId:id,target,text,status:'draft',createdAt:new Date().toISOString()};const a=notes();a.unshift(r);persist(KEY,a);localStorage.removeItem(DRAFT);receiptDetail(r.id);}catch{toast('저장에 실패했습니다. 원문을 복사하여 보관하세요.');}}
const labels={draft:'기기에 보관 · 미전송',sending:'서버 응답 확인 중',unknown:'결과 확인 필요 · 재전송 보류',applied:'서버 반영 확인',review:'검토 필요',partial:'일부 반영 · 검토 필요',excluded:'운영 반영 제외',duplicate:'중복 접수 · 반영 확인 필요',received:'서버 접수 · 반영 대기',rejected:'서버 접수 거절'};
function showInbox(){open(heading('ACTIVITY','처리함','이 기기에 보관한 입력 내역 · 새로고침 후에도 유지')+`<p class="note">다른 휴대폰과 자동 공유되지 않습니다. 서버 반영 여부는 각 기록에서 확인하세요.</p>${notes().map(r=>`<button class="item" onclick="receiptDetail('${r.id}')"><span class="tag">${esc(labels[r.status]||labels.unknown)}</span><h3>${esc(r.target)}</h3><p>${esc(r.text)}</p><small>${esc(new Date(r.updatedAt||r.createdAt).toLocaleString('ko-KR'))}${r.updatedAt?' · 수정됨':''}</small></button>`).join('')||'<p class="empty">아직 보관한 입력이 없습니다.</p>'}`);}
function receiptDetail(id){const r=notes().find(r=>r.id===id);if(!r)return;open(heading('INPUT RESULT',labels[r.status]||labels.unknown,r.target)+`<div class="action-box" style="white-space:pre-wrap">${esc(r.text)}</div><p class="note">보관 번호 ${esc(r.id)}${r.requestId?'<br>서버 요청 '+esc(r.requestId):''}</p>${r.ack?`<p>${esc(r.ack)}</p>`:''}${r.status==='draft'?`<div class="alert">보내기를 누르면 운영 입력으로 접수됩니다. 대상과 내용을 확인하세요.</div><button id="sendNote" class="primary" onclick="sendNote('${r.id}')">확인한 내용 서버로 보내기</button>`:''}${['unknown','sending'].includes(r.status)?'<div class="alert">응답이 확인되지 않아 자동 재전송하지 않습니다. 중복 입력을 피하려면 서버 기록을 먼저 확인해야 합니다.</div>':''}${r.status==='applied'?'<p>업무이력 저장을 확인했습니다. 현재 상태와 일정은 별도 원장 기준이며 자동 변경되지 않습니다.</p>':''}<button class="secondary" onclick="refreshAndShow()">최신 업무 상태 확인</button><button class="secondary" onclick="showInbox()">처리함으로</button>`);}
async function sendNote(id){const r=notes().find(r=>r.id===id);if(!r||r.status!=='draft')return;try{updateNote(id,{status:'sending'});}catch{return toast('원문 보관에 실패하여 전송하지 않았습니다.');}receiptDetail(id);try{const d=await api('/api/write',{op:'safe_write',submissionId:r.submissionId||r.id,text:`${r.target} ${r.text}`,targetHint:r.target,source:'MOBILE',requester:'Emotion'},55000);const status=/REVIEW/i.test(d.status)?(d.applied?'partial':'review'):d.applied?'applied':/EXCLUDED/i.test(d.status)?'excluded':/DUPLICATE/i.test(d.status)?'duplicate':'received';updateNote(id,{status,requestId:d.requestId||'',ack:d.ack||'',respondedAt:new Date().toISOString()});if(d.applied)await refresh();}catch(e){try{updateNote(id,{status:e.status===401||e.status===400?'rejected':'unknown',requestId:e.data?.requestId||'',ack:e.status===401?'인증이 만료되었습니다. 다시 연결하세요.':e.data?.ack||'서버 응답을 확정하지 못했습니다.'});}catch{toast('결과 보관 실패. 서버 기록을 확인하세요.');}}receiptDetail(id);}
async function refreshAndShow(){dialog.close();home();await refresh();}
function stopVoice(){if(recognition){recognition.abort();recognition=null;}}
function voice(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech)return toast('이 브라우저는 음성 인식을 지원하지 않습니다. 키보드의 음성 입력을 사용할 수 있습니다.');if(recognition){stopVoice();return;}recognition=new Speech();recognition.lang='ko-KR';recognition.interimResults=false;recognition.onresult=e=>{if($('draft')){$('draft').value=($('draft').value+' '+e.results[0][0].transcript).trim().slice(0,800);saveDraft();}};recognition.onerror=e=>toast(e.error==='not-allowed'?'마이크 사용 권한이 필요합니다.':'음성 인식에 실패했습니다. 다시 시도하세요.');recognition.onend=()=>{recognition=null;};try{recognition.start();toast('듣고 있습니다. 인식 후 내용을 확인하세요.');}catch{stopVoice();toast('마이크를 시작하지 못했습니다.');}}
function login(){location.href='./login.html';}
async function unlock(){const key=$('appKey').value.trim();if(!key){$('loginHint').textContent='앱 연결 키를 입력하세요.';return;}$('loginHint').textContent='연결 중…';try{await api('/api/unlock',{key});$('appKey').value='';dialog.close();await refresh();if(!live)toast(readMessage);}catch{$('loginHint').textContent='인증하지 못했습니다. 연결 키와 네트워크를 확인하세요.';}}
function grow(){open(heading('GROW','업무 근거 찾기','현재 조회한 이슈에서 검색합니다 · AI 모델 미연결')+`<textarea id="growQuestion" aria-label="그로우 질문" placeholder="예: 미코 상태 알려줘"></textarea><button class="primary" onclick="growAnswer()">현재 기록에서 찾기</button><div id="growResult" aria-live="polite"></div><button class="secondary" onclick="input()">진행 내용 입력하기</button>`);}
function growAnswer(){const raw=$('growQuestion').value.trim();if(!raw){$('growResult').textContent='질문을 입력하세요.';return;}if(!live){$('growResult').textContent='먼저 앱 연결을 완료하고 현재 상태를 불러오세요.';return;}if(/변경|삭제|등록|기록|반영/.test(raw)){$('growResult').textContent='이 화면은 기록 검색입니다. 변경 내용은 현장 입력에서 확인 후 접수하세요.';return;}const q=norm(raw.replace(/알려줘|보여줘|지금|현재|상태|현황|어때|확인/g,'')),found=/오늘|전체/.test(raw)?items:items.filter(x=>q&&(norm(x.customer).includes(q)||q.includes(norm(x.customer))||norm(x.model).includes(q)||q.includes(norm(x.model))));$('growResult').innerHTML=found.length?found.map(card).join(''):'<p>관련 근거를 찾지 못했습니다. 고객명이나 장비명을 입력하세요.</p>';}
function settings(){open(heading('MY HANDSFREE','사용자와 설정',`버전 ${BUILD}`)+`<div class="action-box">${live?'현재 상태 연결됨':'앱 연결 필요'}</div><p>새 기기 최초 등록 때만 관리자 등록키를 한 번 사용합니다. 이후에는 자동 연결되며 다시 인증이 필요할 때만 4자리 PIN을 사용합니다. 푸시 알림은 아직 연결되지 않았습니다.</p><button class="primary" onclick="installApp()">휴대폰에 앱 설치</button><button class="secondary" onclick="login()">사용자 등록 · 연결</button><button class="secondary" onclick="showInbox()">기기에 보관한 입력 확인</button><button class="secondary" onclick="checkUpdate()">앱 업데이트 확인</button><p class="note">오프라인에서는 초안을 보관할 수 있습니다. 서버 전송은 연결 후 직접 확인하여 진행하며 자동 재전송하지 않습니다.</p>`);}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
async function installApp(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;return;}open(heading('INSTALL','휴대폰에 설치','한 번 설치하면 홈 화면에서 열 수 있습니다')+'<p>아이폰: Safari에서 이 주소를 연 뒤 공유 → 홈 화면에 추가.</p><p>안드로이드: Chrome에서 이 주소를 연 뒤 메뉴 → 앱 설치 또는 홈 화면에 추가.</p><p class="note">이미 설치했거나 설치를 지원하지 않는 브라우저에서는 설치 버튼이 나타나지 않을 수 있습니다.</p>');}
async function checkUpdate(){try{const r=await navigator.serviceWorker?.getRegistration('/kmt/');if(!r)return toast('현재 브라우저에서 업데이트 서비스를 사용할 수 없습니다.');await r.update();toast(r.waiting?'새 버전이 준비되었습니다. 앱 창을 모두 닫고 다시 여세요.':'업데이트 확인 완료. 새 버전은 앱을 다시 열 때 적용됩니다.');}catch{toast('업데이트 확인 실패. 네트워크를 확인하세요.');}}
const nav=document.querySelector('.bottom');nav.style.gridTemplateColumns='repeat(5,1fr)';nav.innerHTML=`<button data-page="home" id="homeNav" onclick="home()"><span class="nav-icon">⌂</span>오늘</button><button data-page="work" id="workNav" onclick="work()"><span class="nav-icon">▦</span>업무</button><button onclick="grow()"><span class="nav-icon">✳</span>그로우</button><button class="new" onclick="input()"><span class="nav-icon">＋</span>입력</button><button onclick="showInbox()"><span class="nav-icon">▤</span>처리함</button>`;
const profile=document.createElement('button');profile.className='icon';profile.textContent='나';profile.setAttribute('aria-label','사용자와 설정');profile.onclick=settings;document.querySelector('.top').append(profile);
const style=document.createElement('style');style.textContent=`label{display:block;margin:16px 0;font-size:13px}label input{display:block;width:100%;padding:13px;border:1px solid var(--line);border-radius:12px;margin-top:8px}label textarea{margin-top:8px}input,textarea,select{font-size:16px!important}.item-detail{width:100%;text-align:left;background:none;border:0;padding:0}.item-status{display:flex;align-items:center;gap:6px}.schedule-button{background:white;border:1px solid var(--line);border-radius:6px;padding:8px;font-size:11px}.plan-list li{display:flex;flex-wrap:wrap;gap:12px;padding:12px 0}.brief button{gap:8px;text-align:left}.brief button strong{white-space:nowrap}.top .icon{min-width:38px}.demo{flex-wrap:wrap}.sheet{padding-bottom:calc(26px + env(safe-area-inset-bottom))}.item,.action-box,p{overflow-wrap:anywhere}@media(max-width:380px){.top{padding-left:12px!important;padding-right:12px!important}.kmt-brand{gap:5px!important}.kmt-brand strong{font-size:14px!important}}`;document.head.append(style);
window.addEventListener('online',()=>{toast('연결이 복구되었습니다. 보관한 입력은 처리함에서 확인하세요.');refresh();});
window.addEventListener('offline',()=>{items=[];live=false;readMessage='오프라인 · 초안 보관 가능';banner();if(screen==='home')home();if(screen==='work')work(filter);});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>toast('오프라인 앱 준비에 실패했습니다. 온라인으로 사용할 수 있습니다.'));
