'use strict';
const $=id=>document.getElementById(id);
const statusEl=$('status'),setupEl=$('setup'),logoutEl=$('logout');
const loginParams=new URLSearchParams(location.search),operationsReturn=loginParams.get('mode')==='operations';
function returnUrl(connected=false){return '/handsfree-renewal/?app=renewal12'+(operationsReturn?'&mode=operations':'')+(connected?'&connected=1':'');}
function bindSecretToggles(){document.querySelectorAll('[data-secret]').forEach(button=>{button.onclick=()=>{const input=$(button.dataset.secret);if(!input)return;const show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'숨기기':'보기';button.setAttribute('aria-pressed',show?'true':'false');};});}
async function call(body){const c=new AbortController(),timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch('/api/sa2-auth',{method:body?'POST':'GET',credentials:'include',cache:'no-store',signal:c.signal,headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});let d={};try{d=await r.json();}catch{const e=Error('invalid_response');e.status=r.status;throw e;}if(!r.ok||d.ok!==true){const e=Error(d.error||'auth_failed');e.status=r.status;e.data=d;throw e;}return d;}catch(e){if(e.name==='AbortError'){const timeout=Error('request_timeout');timeout.timeout=true;throw timeout;}throw e;}finally{clearTimeout(timer);}}
function authMessage(e){if(navigator.onLine===false)return '인터넷 연결이 없습니다.';if(e.timeout)return '서버 응답 시간이 초과됐습니다. 다시 눌러 확인하세요.';if(e.status===429)return '연결 시도가 많습니다. 잠시 후 다시 시도하세요.';if(e.status===401)return '이름 또는 PIN을 확인하세요.';if(e.status===403)return e.data?.error==='invalid_origin'?'앱 주소와 서버 연결 설정을 확인하세요.':'이 기기의 접근 권한을 확인하세요.';if(e.status>=500)return '서버가 응답하지 않습니다. 잠시 후 다시 확인하세요.';return '연결에 실패했습니다. 네트워크를 확인하세요.';}
function showSetup(message='이름과 4자리 PIN을 입력하세요.'){setupEl.hidden=false;logoutEl.hidden=true;statusEl.textContent=message;}
function connected(user){setupEl.hidden=true;logoutEl.hidden=false;statusEl.textContent=(user.label||'내 계정')+' · 자동 연결됨';}
async function start(){try{const d=await call();if(d.user)return connected(d.user);showSetup();}catch(e){showSetup(authMessage(e));}}
$('activateBtn').onclick=async()=>{const name=$('displayName').value.trim(),pin=$('pin').value.trim();if(!name){statusEl.textContent='이름을 입력하세요.';return;}if(!/^[0-9]{4}$/.test(pin)){statusEl.textContent='숫자 4자리 PIN을 입력하세요.';return;}$('activateBtn').disabled=true;statusEl.textContent='연결 중…';try{const d=await call({action:'activate',name,pin});$('pin').value='';connected(d.user);statusEl.textContent+=' · HandsFree로 이동합니다.';setTimeout(()=>location.replace(returnUrl(true)),300);}catch(e){statusEl.textContent=authMessage(e);}finally{$('activateBtn').disabled=false;}};
logoutEl.onclick=async()=>{logoutEl.disabled=true;try{await call({action:'logout'});showSetup('이 기기 연결을 해제했습니다.');}catch{statusEl.textContent='연결 해제를 확인하지 못했습니다.';}finally{logoutEl.disabled=false;}};
window.addEventListener('load',()=>{bindSecretToggles();const link=$('returnLink');if(link){link.href=returnUrl();link.textContent=operationsReturn?'HandsFree 운영DB로 돌아가기':'HandsFree Renewal로 돌아가기';}start();});
