'use strict';
const BUILD='2026.09.30.RENEWAL.0.3', KEY='handsfree-renewal-notes-v1', DRAFT='handsfree-renewal-draft-v1';
const main=document.getElementById('main'),dialog=document.getElementById('detail');
let items=[],live=false,personalConnected=false,readPending=null,sourceDate='',lastRead='',screen='home',filter='all',returnFocus=null,readMessage='현재 상태를 불러오는 중…',recognition=null,installPrompt=null;
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(s){return String(s||'').toLowerCase().replace(/[\s\-‐‑–—]/g,'');}
function heading(k,t,sub=''){return `<div class="sheet-head"><div><div class="eyebrow">${esc(k)}</div><h2>${esc(t)}</h2></div><button class="icon" aria-label="상세 닫기" onclick="dialog.close()">×</button></div><div class="sub">${esc(sub)}</div>`;}
function open(html){stopVoice();if(!dialog.open)returnFocus=document.activeElement;$('sheetBody').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
dialog.addEventListener('close',()=>{stopVoice();if(returnFocus?.isConnected)returnFocus.focus();});
function toast(text){clearTimeout(toast.timer);$('toast').hidden=true;let target=$('toast');if(dialog.open){target=$('dialogStatus');if(!target){target=document.createElement('p');target.id='dialogStatus';target.className='alert';target.setAttribute('role','status');$('sheetBody').appendChild(target);}}target.textContent=text;target.hidden=false;if(dialog.open)target.scrollIntoView({block:'nearest'});toast.timer=setTimeout(()=>target.hidden=true,4500);}
function readStore(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch{return fallback;}}
function persist(key,value){localStorage.setItem(key,JSON.stringify(value));if(localStorage.getItem(key)!==JSON.stringify(value))throw Error('storage_failed');}
function notes(){const a=readStore(KEY,[]);return Array.isArray(a)?a:[];}
function updateNote(id,patch){const a=notes(),r=a.find(r=>r.id===id);if(!r)throw Error('missing_note');Object.assign(r,patch);persist(KEY,a);return r;}
async function api(path,body,timeout=25000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(path,{credentials:'same-origin',cache:'no-store',signal:c.signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let d;try{d=await r.json();}catch{throw Error('invalid_response');}if(!r.ok||d.ok!==true){const e=Error(d.error||'request_failed');e.status=r.status;e.data=d;throw e;}return d;}finally{clearTimeout(timer);}}
function active(name){screen=name;document.querySelectorAll('.top-tabs button').forEach(b=>b.classList.toggle('selected',b.dataset.page===name));}
function banner(){document.querySelector('.demo').innerHTML=`<b>수정 버전 ${BUILD}</b><span>${live?'실시간 조회 · ':''}${esc(readMessage)}</span>`;}
async function refresh(){if(readPending)return readPending;readMessage='현재 상태를 불러오는 중…';banner();readPending=(async()=>{try{const d=await api('/api/sa2-real-status');if(d.live!==true||!Array.isArray(d.currentStatus))throw Error('invalid_response');items=d.currentStatus.map((x,id)=>({...x,id}));live=true;personalConnected=d.personalConnected===true;sourceDate=d.sourceLatestDate||'';lastRead=new Date().toLocaleString('ko-KR');readMessage=(d.test?'검증 데이터 · 운영 아님 · ':'')+`${items.length}건 · ${sourceDate||'기준일 미등록'}`+(personalConnected?' · 개인 인증 연결됨':' · 개인 인증 필요');return true;}catch(e){items=[];live=false;personalConnected=false;readMessage=e.status===401?'사용자 등록 · 연결이 필요합니다':'현재 상태를 불러오지 못했습니다. 다시 시도하세요.';return false;}finally{readPending=null;banner();if(screen==='home')home();if(screen==='work'||screen==='projects')projects(filter,$('search')?.value||'');if(screen==='delivery')delivery();}})();return readPending;}
function card(x){return `<article class="item ${x.pendingNoteId?'pending-update':''}"><div class="item-top"><div class="item-status"><span class="tag">${x.pendingNoteId?'서버 확인 중':'현재 진행'}</span><button class="schedule-button" onclick="scheduleReport(${x.id})">계획일정 ↗</button></div><span class="category">${esc(x.process)}</span></div><button class="item-detail" aria-label="${esc(x.customer)} ${esc(x.model)} 업무 상세" onclick="openItem(${x.id})"><h3>${esc(x.customer)}<small>${esc(x.model)}</small></h3><p class="issue">${esc(x.state||'진행내용 미등록')}</p><div class="next"><span>다음 행동 · ${esc(x.nextAction||'확인 필요')}</span><span>›</span></div></button></article>`;}
function reports(){return `<section><div class="section-title"><h2>생산 · 지원 집계</h2></div><div class="report-links"><button onclick="productionReport('month')">▥ 월간생산량<small>집계 연결 확인 ›</small></button><button onclick="productionReport('year')">▤ 연간생산량<small>집계 연결 확인 ›</small></button><button onclick="supportReport()">⇄ 타부서지원<small>누적 집계표 ›</small></button></div></section>`;}
function home(){active('home');const urgentItems=items.filter(x=>x.priority===1),urgent=urgentItems.length,waiting=items.filter(x=>/대기|보류|지연/.test(x.state)).length,focus=urgentItems[0]||items[0];main.innerHTML=`<div class="date">${esc(new Date().toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'long',day:'numeric',weekday:'long'}))}<button class="chip" style="float:right" onclick="refresh()">새로고침</button></div><h1>오늘 확인할 일<br>${live?`<span>${items.length}건이 있습니다</span>`:'<span>연결을 확인하세요</span>'}</h1><p class="lead">납기와 다음 공정에 영향이 큰 순서입니다.</p><section class="brief"><div class="brief-label">가장 먼저 확인할 업무</div>${focus?`<h2>${esc(focus.model)}<br><em>${esc(focus.state||'진행내용 확인')}</em></h2><p>${esc(focus.customer)} · ${esc(focus.process||'공정 미등록')}</p><button onclick="openItem(${focus.id})"><span>다음 행동 · ${esc(focus.nextAction||'확인 필요')}</span><strong>상세 보기</strong></button>`:`<h2>현재 상태 연결을 확인하세요.</h2><button onclick="login()">개인 연결하기 ↗</button>`}</section>${live&&!personalConnected?'<button class="quiet" onclick="login()"><span><strong>개인 인증이 필요합니다</strong><small>생산 실적 · 프로젝트 이력 · 진행내용 입력</small></span><span>연결하기 ›</span></button>':''}<div class="metrics"><button class="metric" onclick="projects('waiting')"><small>대기·보류</small><strong>${live?waiting:'—'}<span>건</span></strong></button><button class="metric" onclick="projects('urgent')"><small>우선순위 1</small><strong>${live?urgent:'—'}<span>건</span></strong></button><button class="metric" onclick="projects()"><small>전체 프로젝트</small><strong>${live?items.length:'—'}<span>건</span></strong></button></div>${focus?`<div class="quick-actions"><button class="quick-action" onclick="input(${focus.id})"><span>＋ 이 업무에 진행 내용 입력</span><small>저장 즉시 화면에 표시</small></button><button class="voice-action" onclick="voiceInput(${focus.id})" aria-label="이 업무에 음성으로 진행 내용 입력">● 음성 입력</button></div>`:''}${reports()}<div class="section-title"><h2>공정 신호</h2><span>막힌 순서</span></div>${items.map(card).join('')}<p class="source">${live?`현재 상태 기준일 ${esc(sourceDate||'미등록')} · 조회 ${esc(lastRead)}`:esc(readMessage)}<br>담당·완료 여부는 원본 기록을 기준으로 확인합니다.</p>`;banner();}
function work(f='all',query=''){active('projects');filter=f;main.innerHTML=`<h1>프로젝트 <span>한눈에</span></h1><p class="lead">현재 관리 업무를 검색합니다.</p><div class="search"><input id="search" aria-label="고객 또는 장비 검색" value="${esc(query)}" placeholder="고객명 · 장비명 · 상태" oninput="renderList()"></div><div class="tabs">${[['all','전체'],['waiting','대기·보류'],['urgent','우선순위 1']].map(([v,t])=>`<button class="chip ${f===v?'active':''}" onclick="projects('${v}')">${t}</button>`).join('')}</div><div id="list"></div>`;renderList();}
function projects(f='all',query=''){active('projects');work(f,query);screen='projects';active('projects');}
function delivery(){active('delivery');const rows=items.slice().sort((a,b)=>String(a.due||'9999').localeCompare(String(b.due||'9999')));main.innerHTML=`<div class="date">CUSTOMER PROMISES</div><h1>납기 <span>출고 약속</span></h1><p class="lead">프로젝트를 누르면 원본 계획일정 전체를 확인합니다.</p><div class="delivery-list">${rows.map(x=>`<article class="item"><button class="item-detail" onclick="scheduleReport(${x.id})"><div class="delivery-date">${esc(x.due||'일정 확인')}</div><h3>${esc(x.customer)}<small>${esc(x.model)}</small></h3><p class="issue">${esc(x.state||'진행내용 미등록')}</p><div class="next"><span>${esc(x.process||'공정 미등록')}</span><span>계획 보기 ›</span></div></button></article>`).join('')||'<p class="empty">연결된 납기 정보가 없습니다.</p>'}</div>`;}
function records(){active('records');showInbox();}
function renderList(){const q=norm($('search').value),a=items.filter(x=>(filter!=='waiting'||/대기|보류|지연/.test(x.state))&&(filter!=='urgent'||x.priority===1)&&norm([x.customer,x.model,x.state,x.cause,x.orderId].join(' ')).includes(q));$('list').innerHTML=a.length?a.map(card).join(''):`<div class="empty">${live?'일치하는 업무가 없습니다.':esc(readMessage)}</div>`;}
function openItem(id){const x=items[id];if(!x)return toast('최신 상태를 다시 불러오세요.');open(heading(x.process,x.customer,x.model)+`<h4>최근 진행내용</h4><div class="action-box">${esc(x.state||'미등록')}</div><h4>진행 시작 · 지속</h4><p>${esc(x.since||'미등록')} · ${Number.isFinite(x.days)?x.days+'일째':'기간 미확인'}</p><h4>기존 원인 / 이슈</h4><p>${esc(x.cause||'미등록')}</p><h4>다음 행동</h4><p>${esc(x.nextAction||'미등록')}</p><p class="note">${esc(x.issueId)} · ${esc(x.issueStatus)} · 원본 최신 ${esc(x.sourceLatestUpdate||sourceDate)}</p><button class="primary" onclick="input(${id})">이 업무에 진행 내용 입력</button><button class="secondary" onclick="scheduleReport(${id})">계획일정 확인</button>`);}
function unavailable(title,description){open(heading('연결 상태',title,'실제 데이터 연결이 필요합니다')+`<div class="alert">${esc(description)}</div><p>값을 0 또는 완료로 대신 표시하지 않습니다.</p><button class="secondary" onclick="dialog.close()">닫기</button>`);}
function productionReport(mode){unavailable(mode==='month'?'월간생산량':'연간생산량','현재 조회 서비스에 생산 완료일·완료 수량이 없어 실적을 집계할 수 없습니다.');}
function supportReport(){unavailable('타부서지원 누적 집계표','현재 조회 서비스에 지원 부서·지원 시간·기준일이 연결되지 않았습니다.');}
let planRequest=0;
async function scheduleReport(id){
 const x=items[id];if(!x)return;
 const request=++planRequest;
 open(heading('계획일정',x.customer,x.model)+'<p id="planResult">원본 계획을 불러오는 중…</p>');
 const result=$('planResult');
 if(!x.orderId){result.textContent='프로젝트 ID가 없어 계획을 안전하게 연결할 수 없습니다.';return;}
 try{
  const d=await api('/api/sa2-lifecycle',{action:'plans',orderId:x.orderId});
  if(request!==planRequest||!result.isConnected||!dialog.open)return;
  if(d.orderId!==x.orderId||!Array.isArray(d.plans))throw Error('invalid_plans');
  result.outerHTML='<div class="alert">계획은 완료 실적이 아닙니다. 일정 수정은 개인계정 권한과 변경이력 연결 검증이 필요합니다.</div><p>'+esc(x.orderId)+'</p>'+
    (d.plans.length?d.plans.map(r=>'<article class="item"><b>'+esc(r[3])+' · '+esc(r[10])+'</b><p>'+esc(r[11]||'상태 미등록')+'</p></article>').join(''):'<p>이 프로젝트 ID에 연결된 계획이 없습니다.</p>');
 }catch{if(request===planRequest&&result.isConnected)result.textContent='계획을 불러오지 못했습니다. 연결을 확인한 뒤 다시 여세요.';}
}
function input(id){const x=typeof id==='object'?id:items[id],d=readStore(DRAFT,{}),target=x?`${x.orderId?x.orderId+' · ':''}${x.customer} · ${x.model}`:d.target||'',draftText=x&&d.target&&d.target!==target?'':d.text||'';open(heading('FIELD NOTE','진행내용 입력',x?.issueId?'입력한 첫 줄을 현재 업무 카드에도 바로 표시합니다.':'기기에 보관한 뒤 내용을 확인하여 서버로 보냅니다')+`<label>입력 대상<input id="inputTarget" aria-label="입력 대상" maxlength="160" value="${esc(target)}" placeholder="고객명 · 장비명" oninput="saveDraft()"></label><label>진행내용<textarea id="draft" aria-label="진행 내용" maxlength="800" placeholder="바뀐 진행내용을 입력하세요." oninput="saveDraft()">${esc(draftText)}</textarea></label><input id="inputIssueId" type="hidden" value="${esc(x?.issueId||'')}"><input id="inputOrderId" type="hidden" value="${esc(x?.orderId||'')}"><input id="inputNextAction" type="hidden" value="${esc(x?.nextAction||'')}"><input id="inputIssueStatus" type="hidden" value="${esc(x?.issueStatus||'OPEN')}"><button class="chip" onclick="voice()">◉ 음성 입력</button><p id="inputHint" class="note">${draftText?'보관한 초안을 불러왔습니다.':x?.issueId?'첫 줄은 현재 진행으로 표시하고, 다음 행동·일정은 그대로 둡니다.':'입력 원문은 이 기기에 보관됩니다.'}</p><button class="primary" onclick="saveAndSendNote()">서버로 보내고 바로 반영</button><button class="secondary" onclick="saveNote()">기기에만 보관</button><p class="note">서버 저장과 재조회를 확인한 뒤 업무 카드를 자동으로 갱신합니다.</p>`);}
function saveDraft(){try{persist(DRAFT,{target:$('inputTarget').value,text:$('draft').value});$('inputHint').textContent='이 기기에 초안 보관됨';}catch{$('inputHint').textContent='기기 저장에 실패했습니다. 화면을 닫기 전에 원문을 복사하세요.';}}
function saveNote(){const target=$('inputTarget').value.trim(),text=$('draft').value.trim();if(!target||!text){$('inputHint').textContent='입력 대상과 진행 내용을 모두 작성하세요.';return;}try{const id=crypto.randomUUID(),r={id,submissionId:id,target,text,status:'draft',createdAt:new Date().toISOString(),issueId:$('inputIssueId')?.value||'',orderId:$('inputOrderId')?.value||'',displayState:text.split(/\r?\n/).map(v=>v.trim()).find(Boolean)?.slice(0,80)||'',nextAction:$('inputNextAction')?.value||'',issueStatus:$('inputIssueStatus')?.value||'OPEN'};const a=notes();a.unshift(r);persist(KEY,a);localStorage.removeItem(DRAFT);receiptDetail(r.id);return r.id;}catch{toast('저장에 실패했습니다. 원문을 복사하여 보관하세요.');}}
function previewProgress(id){const r=notes().find(x=>x.id===id),i=items.findIndex(x=>x.issueId===r?.issueId);if(!r||i<0||!r.displayState||items[i].pendingNoteId===id)return;try{updateNote(id,{previousState:items[i].state||'',previewedAt:new Date().toISOString()});}catch{}items[i]={...items[i],state:r.displayState,pendingNoteId:id};if(screen==='home')home();if(screen==='work'||screen==='projects')projects(filter,$('search')?.value||'');if(screen==='delivery')delivery();}
function restoreProgressPreview(id){const r=notes().find(x=>x.id===id),i=items.findIndex(x=>x.pendingNoteId===id);if(i<0)return;items[i]={...items[i],state:r?.previousState||items[i].state,pendingNoteId:''};if(screen==='home')home();if(screen==='work'||screen==='projects')projects(filter,$('search')?.value||'');if(screen==='delivery')delivery();}
async function saveAndSendNote(){const id=saveNote();if(id)await sendNote(id);}
const labels={draft:'기기에 보관 · 미전송',sending:'서버 응답 확인 중',unknown:'결과 확인 필요 · 재전송 보류',applied:'업무이력 저장 · 재조회 확인',saved_unverified:'서버 저장 응답 · 재조회 확인 필요',review:'검토 필요',partial:'일부 반영 · 검토 필요',excluded:'운영 반영 제외',duplicate:'중복 접수 · 반영 확인 필요',received:'서버 접수 · 반영 대기',rejected:'서버 접수 거절'};
function showInbox(){const all=notes(),done=r=>r.status==='applied'&&!!r.verifiedAt;const rows=a=>a.map(r=>`<button class="item" onclick="receiptDetail('${r.id}')"><span class="tag">${esc(r.status==='applied'&&!r.verifiedAt?labels.saved_unverified:(labels[r.status]||labels.unknown))}</span><h3>${esc(r.target)}</h3><p>${esc(r.text)}</p><small>${esc(new Date(r.updatedAt||r.createdAt).toLocaleString('ko-KR'))}${r.updatedAt?' · 수정됨':''}</small></button>`).join('')||'<p class="empty">기록이 없습니다.</p>';open(heading('ACTIVITY','처리함','이 기기의 원문과 이력을 보존합니다')+'<p class="note">업무 카드에서 입력한 진행내용은 이력 저장과 현재 진행 표시를 함께 확인합니다. 다음 행동·일정은 그대로 유지합니다.</p><h3>확인 필요</h3>'+rows(all.filter(r=>!done(r)))+'<h3>저장 완료</h3>'+rows(all.filter(done)));}
function receiptDetail(id){const r=notes().find(r=>r.id===id);if(!r)return;open(heading('INPUT RESULT',r.status==='applied'&&!r.verifiedAt?labels.saved_unverified:(labels[r.status]||labels.unknown),r.target)+`<div class="action-box" style="white-space:pre-wrap">${esc(r.text)}</div><p class="note">보관 번호 ${esc(r.id)}${r.requestId?'<br>서버 요청 '+esc(r.requestId):''}</p>${r.ack?`<p>${esc(r.ack)}</p>`:''}${r.status==='draft'?`<div class="alert">보내기를 누르면 업무이력으로 저장되고, 연결된 업무 카드의 현재 진행도 함께 바뀝니다.</div><button id="sendNote" class="primary" onclick="sendNote('${r.id}')">서버로 보내고 바로 반영</button>`:''}${['unknown','sending'].includes(r.status)?'<div class="alert">응답이 확인되지 않아 자동 재전송하지 않습니다. 중복 입력을 피하려면 서버 기록을 먼저 확인해야 합니다.</div>':''}${r.status==='applied'?'<p>'+(r.issueId?'업무이력 저장과 현재 진행 표시를 확인했습니다. 다음 행동·일정은 그대로입니다.':'업무이력 저장을 확인했습니다.')+'</p>':''}<button class="secondary" onclick="refreshAndShow()">최신 업무 상태 확인</button><button class="secondary" onclick="showInbox()">처리함으로</button>`);}
async function sendNote(id){const r=notes().find(r=>r.id===id);if(!r||r.status!=='draft')return;if(!canSendNote(r))return;previewProgress(id);if(navigator.onLine===false){restoreProgressPreview(id);return toast('오프라인입니다. 수정 내용은 기기에 보관했습니다.');}try{updateNote(id,{status:'sending'});}catch{restoreProgressPreview(id);return toast('원문 보관에 실패하여 전송하지 않았습니다.');}receiptDetail(id);try{const d=await api('/api/sa2-write',{op:'safe_write',submissionId:r.submissionId||r.id,text:`${r.target} ${r.text}`,targetHint:r.target,source:'MOBILE',requester:'Emotion'},55000);const status=/REVIEW/i.test(d.status)?(d.applied?'partial':'review'):d.applied?'saved_unverified':/EXCLUDED/i.test(d.status)?'excluded':/DUPLICATE/i.test(d.status)?'duplicate':'received';const messages={partial:'일부 업무이력은 저장됐고 일부는 검토가 필요합니다.',saved_unverified:'서버 저장 성공. 원본 기록과 최신 화면을 자동으로 다시 확인합니다.',review:'자동 반영하지 않고 검토 대상으로 접수했습니다.',excluded:'운영 기록 반영 제외로 접수했습니다.',duplicate:'중복 가능성이 있어 기존 서버 기록을 확인합니다.',received:'서버가 요청을 접수했습니다. 저장 상태를 자동으로 다시 확인합니다.'};updateNote(id,{status,requestId:d.requestId||'',ack:d.ack||messages[status],respondedAt:new Date().toISOString()});receiptDetail(id);if(d.applied)toast('화면에 반영했습니다. 서버 원본을 확인 중입니다.');if(typeof scheduleEventReceiptCheck==='function')scheduleEventReceiptCheck(id,300,false);else if(d.applied&&typeof verifyEventNote==='function')verifyEventNote(id);}catch(e){try{const rejected=[400,401,403].includes(e.status);updateNote(id,{status:rejected?'rejected':'unknown',requestId:e.data?.requestId||'',ack:appError(e)});if(rejected)restoreProgressPreview(id);receiptDetail(id);if(!rejected&&typeof scheduleEventReceiptCheck==='function')scheduleEventReceiptCheck(id,1500,false);}catch{toast('결과 보관 실패. 서버 기록을 확인하세요.');}}}
async function refreshAndShow(){dialog.close();home();await refresh();}
function stopVoice(){if(recognition){recognition.abort();recognition=null;}}
function voice(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech)return toast('이 브라우저는 음성 인식을 지원하지 않습니다. 키보드의 음성 입력을 사용할 수 있습니다.');if(recognition){stopVoice();return;}recognition=new Speech();recognition.lang='ko-KR';recognition.interimResults=false;recognition.onresult=e=>{if($('draft')){$('draft').value=($('draft').value+' '+e.results[0][0].transcript).trim().slice(0,800);saveDraft();}};recognition.onerror=e=>toast(e.error==='not-allowed'?'마이크 사용 권한이 필요합니다.':'음성 인식에 실패했습니다. 다시 시도하세요.');recognition.onend=()=>{recognition=null;};try{recognition.start();toast('듣고 있습니다. 인식 후 내용을 확인하세요.');}catch{stopVoice();toast('마이크를 시작하지 못했습니다.');}}
function login(){location.href='./login.html';}
async function unlock(){const key=$('appKey').value.trim();if(!key){$('loginHint').textContent='앱 연결 키를 입력하세요.';return;}$('loginHint').textContent='연결 중…';try{await api('/api/unlock',{key});$('appKey').value='';dialog.close();await refresh();if(!live)toast(readMessage);}catch{$('loginHint').textContent='인증하지 못했습니다. 연결 키와 네트워크를 확인하세요.';}}
function grow(){open(heading('GROW','운영DB 근거 찾기','현재 상태와 프로젝트 원장을 다시 조회해 답합니다')+`<textarea id="growQuestion" aria-label="그로우 질문" placeholder="예: 미코 상태와 다음 행동 알려줘"></textarea><button id="growSearch" class="primary" onclick="growAnswer()">운영DB에서 찾기</button><div id="growResult" aria-live="polite"></div><button class="secondary" onclick="input()">진행 내용 입력하기</button>`);}
async function growAnswer(){const raw=$('growQuestion').value.trim(),result=$('growResult');if(!raw){result.textContent='질문을 입력하세요.';return;}if(!live){result.textContent='먼저 앱 연결을 완료하고 현재 상태를 불러오세요.';return;}if(/변경|삭제|등록|저장|반영|수정해|바꿔/.test(raw)){result.textContent='이 화면은 운영DB 조회입니다. 변경은 업무 상세의 상태 수정 또는 현장 입력에서 확인 후 진행하세요.';return;}result.textContent='운영DB를 다시 조회하는 중…';try{const projects=await getAppProjects(),rawNorm=norm(raw),q=norm(raw.replace(/알려줘|보여줘|지금|현재|상태|현황|어때|확인|다음행동|일정/g,'')),all=/오늘|전체|업무/.test(raw);const found=projects.filter(p=>all||[p.orderId,p.customer,p.model,p.pm].some(v=>v&&rawNorm.includes(norm(v)))||(q&&norm([p.orderId,p.customer,p.model,p.state,p.pm].join(' ')).includes(q))).slice(0,20);const current=new Map(items.map(x=>[x.orderId,x]));result.innerHTML=found.length?'<p class="note">운영DB 재조회 '+esc(new Date().toLocaleString('ko-KR'))+' · 현재 상태 기준 '+esc(sourceDate||'미등록')+'</p>'+found.map(p=>{const x=current.get(p.orderId);return '<button class="item" data-grow-project="'+esc(p.orderId)+'"><b>'+esc(p.customer)+' · '+esc(p.model)+'</b><p>현재 '+esc(x?.state||p.state||'미등록')+'</p><p>다음 행동 '+esc(x?.nextAction||'상세에서 확인')+'</p><small>Project ID '+esc(p.orderId)+' · PM '+esc(p.pm||'미등록')+'</small></button>';}).join(''):'<p>운영DB에서 관련 프로젝트를 찾지 못했습니다. 고객명·장비명·Project ID로 다시 검색하세요.</p>';result.querySelectorAll('[data-grow-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.growProject));}catch(e){result.textContent=appError(e);}}
function settings(){open(heading('MY HANDSFREE','사용자와 설정',`버전 ${BUILD}`)+`<div class="action-box">${live?'현재 상태 연결됨':'앱 연결 필요'}</div><p>이름과 4자리 PIN으로 연결합니다. 연결 후에는 180일 동안 자동 유지됩니다. 푸시 알림은 아직 연결되지 않았습니다.</p><button class="primary" onclick="installApp()">휴대폰에 앱 설치</button><button class="secondary" onclick="login()">사용자 등록 · 연결</button><button class="secondary" onclick="showInbox()">기기에 보관한 입력 확인</button><button class="secondary" onclick="checkUpdate()">앱 업데이트 확인</button><p class="note">오프라인에서는 초안을 보관할 수 있습니다. 서버 전송은 연결 후 직접 확인하여 진행하며 자동 재전송하지 않습니다.</p>`);}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
async function installApp(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;return;}open(heading('INSTALL','휴대폰에 설치','한 번 설치하면 홈 화면에서 열 수 있습니다')+'<p>아이폰: Safari에서 이 주소를 연 뒤 공유 → 홈 화면에 추가.</p><p>안드로이드: Chrome에서 이 주소를 연 뒤 메뉴 → 앱 설치 또는 홈 화면에 추가.</p><p class="note">이미 설치했거나 설치를 지원하지 않는 브라우저에서는 설치 버튼이 나타나지 않을 수 있습니다.</p>');}
async function checkUpdate(){try{const r=await navigator.serviceWorker?.getRegistration('/handsfree-renewal/');if(!r)return toast('현재 브라우저에서 업데이트 서비스를 사용할 수 없습니다.');await r.update();toast(r.waiting?'새 버전이 준비되었습니다. 앱 창을 모두 닫고 다시 여세요.':'업데이트 확인 완료. 새 버전은 앱을 다시 열 때 적용됩니다.');}catch{toast('업데이트 확인 실패. 네트워크를 확인하세요.');}}
function voiceInput(id){if(!personalConnected)return login();input(id);setTimeout(()=>{if($('draft'))voice();},80);}
const profile=document.createElement('button');profile.className='icon';profile.textContent='나';profile.setAttribute('aria-label','사용자와 설정');profile.onclick=settings;document.querySelector('.top').append(profile);
const style=document.createElement('style');style.textContent=`label{display:block;margin:16px 0;font-size:13px}label input{display:block;width:100%;padding:13px;border:1px solid var(--line);border-radius:12px;margin-top:8px}label textarea{margin-top:8px}input,textarea,select{font-size:16px!important}.item-detail{width:100%;text-align:left;background:none;border:0;padding:0}.item-status{display:flex;align-items:center;gap:6px}.schedule-button{background:white;border:1px solid var(--line);border-radius:6px;padding:8px;font-size:11px}.plan-list li{display:flex;flex-wrap:wrap;gap:12px;padding:12px 0}.brief button{gap:8px;text-align:left}.brief button strong{white-space:nowrap}.top .icon{min-width:38px}.demo{flex-wrap:wrap}.sheet{padding-bottom:calc(26px + env(safe-area-inset-bottom))}.item,.action-box,p{overflow-wrap:anywhere}@media(max-width:380px){.top{padding-left:12px!important;padding-right:12px!important}.kmt-brand{gap:5px!important}.kmt-brand strong{font-size:14px!important}}`;document.head.append(style);
// Resume reads only: never retry a write, and never invalidate an open editor's item IDs.
let resumeReadNeeded=false,lastResumeRead=0;
function resumeRead(){
 if(document.visibilityState==='hidden'||navigator.onLine===false)return;
 if(dialog.open){resumeReadNeeded=true;return;}
 if(Date.now()-lastResumeRead<3000)return;
 resumeReadNeeded=false;lastResumeRead=Date.now();refresh();
}
window.addEventListener('focus',resumeRead);
document.addEventListener('visibilitychange',resumeRead);
dialog.addEventListener('close',()=>{if(resumeReadNeeded)resumeRead();});
window.addEventListener('online',()=>{toast('연결이 복구되었습니다. 보관한 입력은 처리함에서 확인하세요.');resumeRead();});
window.addEventListener('offline',()=>{items=[];live=false;readMessage='오프라인 · 초안 보관 가능';banner();if(screen==='home')home();if(screen==='work')work(filter);});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>toast('오프라인 앱 준비에 실패했습니다. 온라인으로 사용할 수 있습니다.'));
