const compactStyle=document.createElement('style');compactStyle.textContent='.top{padding:16px 24px 12px;gap:10px}.top>div{margin-right:auto}.demo{margin-bottom:12px}h1{font-size:25px;margin-top:6px}.lead{margin-bottom:16px}.brief{padding:16px}.brief h2{margin:8px 0 10px;font-size:17px}.brief button{padding-top:10px}.metrics{margin:15px 0 18px;padding-bottom:14px}.metric strong{font-size:24px}.item{padding:14px}.bottom button{min-height:44px}';document.head.append(compactStyle);
const reportStyle=document.createElement('style');reportStyle.textContent=`
.report-links{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0 0 22px}.report-links button{border:1px solid var(--line);background:#fff;border-radius:12px;padding:13px 10px;min-height:76px;text-align:left;font-size:12px;font-weight:650;line-height:1.5}.report-links small{display:block;font-size:10px;color:var(--muted);font-weight:400;margin-top:5px}.report-links .report-symbol{display:block;color:var(--green);font-size:17px;margin-bottom:5px}.report-controls{display:flex;gap:8px;align-items:center;margin:15px 0;flex-wrap:wrap}.report-controls select{padding:10px;border:1px solid var(--line);border-radius:8px;background:white}.report-total{display:flex;justify-content:space-between;gap:10px;background:#edf5ef;border-radius:12px;padding:16px}.report-total small{display:block;font-size:11px;color:var(--muted);margin-bottom:5px}.report-total strong{font-size:23px}.report-table{border-collapse:collapse;width:100%;font-size:12px;margin-top:16px}.report-table caption{text-align:left;font-weight:650;padding:10px 0}.report-table th,.report-table td{padding:11px 5px;border-bottom:1px solid var(--line);text-align:right}.report-table th:first-child,.report-table td:first-child{text-align:left}.report-table th{color:var(--muted);font-weight:500}.report-table tfoot{font-weight:750}.bar-row{display:grid;grid-template-columns:28px 1fr 46px;gap:10px;align-items:center;font-size:11px;margin:10px 0}.bar-track{background:#edf1ef;height:9px;border-radius:5px;overflow:hidden}.bar-fill{background:#38866e;height:100%;border-radius:5px}.report-note{font-size:11px!important;color:var(--muted);line-height:1.7}.action-box small,.action-box span{display:block;color:var(--muted);font-size:11px}.action-box strong{display:block;font-size:28px;margin:3px 0}.month-list{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.month-list>div,.year-totals>div{background:#f7f9fc;border:1px solid var(--line);border-radius:10px;padding:10px}.month-list span,.month-list small{display:block}.month-list span{font-size:17px;font-weight:750;margin-top:4px}.month-list small{font-size:10px;color:var(--muted)}.year-totals{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.year-totals>div{display:flex;justify-content:space-between}.project-summary{display:flex;flex-direction:column;gap:5px;background:#edf3fc;border-radius:12px;padding:14px}.progress-history .item p{margin:0 0 8px;white-space:pre-wrap}
`;document.head.append(reportStyle);
const kmtStyle=document.createElement('style');
kmtStyle.textContent=`
:root{--ink:#182b46;--muted:#61728a;--line:#dce4ee;--green:#205bbb;--bg:#e9eef5;--orange:#a04420}
body{background:var(--bg);font-family:'Segoe UI','Malgun Gothic',system-ui,sans-serif}.app{background:#f5f7fb}
.top{padding:20px 22px 16px;background:white;border-top:4px solid #205bbb;border-bottom:1px solid var(--line)}.kmt-brand{display:flex;align-items:center;gap:11px}.kmt-monogram{font-size:27px;font-weight:900;letter-spacing:-2px;color:#194b96;border-right:1px solid #dce4ee;padding-right:12px;line-height:1.2}.kmt-logo-crop{display:block;position:relative;width:94px;height:50px;overflow:hidden;flex-shrink:0}.kmt-original-logo{display:block;position:absolute;width:148px;height:105px;max-width:none;left:-32px;top:-47px;padding:0;border:0}.kmt-brand strong{display:block;font-size:16px;letter-spacing:-.5px}.kmt-brand small{display:block;font-size:10px;color:var(--muted);margin-top:3px;letter-spacing:.4px}.top .icon{border-radius:12px;width:38px;height:38px;flex-shrink:0;background:#f7f9fc;border-color:#e5ebf3}.top>div{min-width:0}
.demo{margin:0;padding:9px 22px 15px;background:linear-gradient(#fff,#f5f7fb);font-size:10px;gap:8px}.demo b{color:#4a6387}main{padding:0 22px}.date{font-size:11px;font-weight:600;color:#657790}h1{font-size:26px;letter-spacing:-1px;line-height:1.4;margin:8px 0 4px}h1 span{font-weight:500}.lead{font-size:12px;margin-bottom:18px;color:#64758c}
.brief{border-radius:16px;background:linear-gradient(115deg,#162d50,#214b7e);padding:18px 18px 14px;box-shadow:0 8px 18px #173d6712}.brief:after{border-radius:16px;transform:rotate(35deg);border-color:#ffffff14;width:160px;height:160px;top:-65px;right:-55px}.brief-label{font-size:10px;letter-spacing:1.2px;color:#c2d8f7}.brief .spark{color:#9fc7ff}.brief h2{font-size:17px;line-height:1.7;font-weight:500;margin:10px 0 12px}.brief h2 em{color:#d3e6ff;font-weight:750}.brief button{color:#d5e3f7;min-height:34px;font-size:11px}
.metrics{gap:9px;margin:14px 0 24px;padding:0;border:0}.metric,.metric:first-child{padding:12px 11px;border:1px solid var(--line);border-radius:12px;background:white}.metric:last-child{border:1px solid var(--line)}.metric small{font-size:11px}.metric strong{font-size:27px;font-variant-numeric:tabular-nums;margin-top:6px}.metric strong span{font-size:11px}.section-title{margin-bottom:10px}.section-title h2{font-size:15px}.section-title>span{font-size:10px}
.report-links{gap:7px;margin-bottom:24px}.report-links button{border-radius:12px;padding:12px 10px;font-size:12px;min-height:110px}.report-links small{font-size:10px;line-height:1.6;color:#62738a}.report-links .report-symbol{width:28px;height:28px;background:#edf3fc;border-radius:8px;display:grid;place-items:center;font-size:17px;margin-bottom:8px}
.item{border-radius:12px;box-shadow:0 3px 10px #21395004;padding:13px 14px;margin-bottom:10px}.item:hover{transform:none;box-shadow:0 4px 14px #2139500c;border-color:#b8cbe4}.item h3{font-size:16px;margin:12px 0 7px}.item h3 small{font-family:ui-monospace,Consolas,monospace;font-size:11px}.tag{border-radius:5px;background:#fff0e9;color:#a04420;padding:5px 7px}.tag.green{background:#edf3fc;color:#275790}.category{font-size:10px;color:#64758c}.issue{color:#51637a;font-size:12px;margin-bottom:12px}.next{border-color:#edf1f7;color:#20569f;font-size:11px}.schedule-button{background:#f7f9fd;border-color:#dae5f3;color:#285995;min-height:36px}.quiet{background:#eaf0f8;border:1px solid #dbe5f2;border-radius:11px}.source{color:#65758b}
.bottom{background:#fffffff5;border-color:#dce4ee;padding-top:9px;box-shadow:0 -4px 18px #203b5d05}.bottom button{color:#67778e;font-size:10px;gap:3px}.bottom button.selected{color:#1d55a6}.bottom button.selected .nav-icon{background:#edf3fc;border-radius:9px;min-width:40px}.new .nav-icon{background:#205bbb}.nav-icon{font-size:21px}.chip.active{background:#214f91;border-color:#214f91}.chip{min-height:36px}.search input{border-radius:11px;background:white}
dialog{color:var(--ink);box-shadow:0 18px 90px #10284630}dialog::backdrop{background:#13284480}.sheet{padding:12px 22px 26px}.sheet h2{font-size:23px}.sheet h4{color:#586d89}.sheet .sub{line-height:1.7}.action-box,.schedule-summary,.report-total{background:#edf3fc;color:#203f6d}.schedule-summary strong{color:#1e4f96}.plan-step{background:#eef4fc;border-color:#cbdcf1;color:#205bbb}.plan-list li:not(:last-child):before{background:#d6e2f2}.plan-date{color:#28558f}.primary{background:#205bbb}.secondary{color:#275790;border-color:#d6e2f2}.alert{background:#fff4e9;color:#874919}.bar-fill{background:#3876cf}.bar-track{background:#edf2fa}.timeline{border-color:#d6e2f2}.timeline p{color:#516985}.timeline p:before{background:#7a9fcf}.toast{background:#203f6d}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #679ff0;outline-offset:3px}.desktop-note{color:#5b7190}.desktop-note b{color:#204f94}.kmt-side-label{font-size:10px;letter-spacing:2px;color:#60799b;margin-bottom:12px}
@media(min-width:760px){.app{border-radius:22px;box-shadow:0 20px 65px #1c3b6210}.bottom{border-radius:0 0 22px 22px}.desktop-note{top:105px}}@media(max-width:360px){main{padding:0 16px}.top{padding:16px}.demo{padding-left:16px;padding-right:16px}.kmt-monogram{font-size:23px}.kmt-brand{gap:8px}.kmt-logo-crop{display:block;position:relative;width:94px;height:50px;overflow:hidden;flex-shrink:0}.kmt-original-logo{display:block;position:absolute;width:148px;height:105px;max-width:none;left:-32px;top:-47px;padding:0;border:0}.kmt-brand strong{font-size:14px}.report-links button{padding:10px 7px}.item-top{gap:4px}}
`;
document.head.append(kmtStyle);
document.querySelector('.top>div').innerHTML='<div class="kmt-brand"><span class="kmt-logo-crop"><img class="kmt-original-logo" alt="케이엠텍 KMT 로고" src="./kmt-mobile-logo.png"></span><div><strong>HandsFree Renewal</strong><small>케이엠텍 · 생산관리</small></div></div><div class="eyebrow">YOUR WORK, AT A GLANCE <span class="version-badge">Renewal 0.12 Preview</span></div>';
document.querySelector('.desktop-note').innerHTML='<b>현장의 흐름을,<br>한눈에.</b>장비별 현재 상태와 다음 행동을 확인하세요.<br><br>입력 내역은 처리함에서 다시 확인할 수 있습니다.';home();refresh();
