import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {loadSchedule} from './schedule.test.mjs';
const c=loadSchedule();c.Utilities.formatDate=d=>d.toISOString().slice(0,10);vm.runInContext(fs.readFileSync(new URL('../apps-script/HF_LIGHT_APP.gs',import.meta.url),'utf8'),c);
const row=['ISS-test',46276,'이슈','PROJECT-01','고객','장비','조립','E-original','OPEN',46276,'','',12,true,'search','immutable note','조립대기','2026-09-11','부품 확인'];
const s={rows:[[],row],formulas:[[],[]],issueId:391424214,audit:[],auditId:1907280002,sheetIds:[391424214]};
const b={action:'edit',issueId:'ISS-test',orderId:'PROJECT-01',expected:c.hfLsHash_(row),state:'검수대기',nextAction:'검수 진행',status:'OPEN',reason:'조립 완료 확인',requestId:'issue-test-00000001',actor:{sub:'123',email:'owner@test'}};
const built=c.hfAppIssueBuild_(s,b,'2026-09-28T08:00:00Z');assert.equal(built.after[0],row[0]);assert.equal(built.after[3],row[3]);assert.equal(built.after[7],row[7]);assert.equal(built.after[15],row[15]);assert.equal(built.after[16],'검수대기');assert.equal(built.after[13],true);assert.equal(built.requests.at(-1).appendCells.sheetId,1907280002);
const audit=built.requests.at(-1).appendCells.rows[0].values.map(v=>v.userEnteredValue.stringValue);s.audit=[Array.from(c.HF_LS.headers),audit];s.rows[1]=Array.from(built.after);
assert.equal(c.hfAppIssueBuild_(s,b,'now').requests.length,0);
assert.throws(()=>c.hfAppIssueBuild_(s,{...b,reason:'changed'},'now'),/request_conflict/);
assert.throws(()=>c.hfAppIssueBuild_(s,{...b,requestId:'issue-test-00000002'},'now'),/stale_record/);
assert.throws(()=>c.hfAppIssueReceipt_(s,{...b,actor:{sub:'other'}}),/forbidden/);
const fresh={...b,requestId:'issue-test-00000002',expected:c.hfLsHash_(s.rows[1]),status:'CLOSED',nextAction:''};const close=c.hfAppIssueBuild_(s,fresh,'2026-09-28T08:00:00Z');assert.equal(close.after[13],false);assert.equal(close.after[11],'2026-09-28');assert.ok(close.requests.some(r=>r.updateCells?.rows[0].values[0].userEnteredValue?.boolValue===false));
s.formulas[1][16]='=A1';assert.throws(()=>c.hfAppIssueBuild_(s,fresh,'2026-09-28T08:00:00Z'),/formula_cell/);s.formulas[1][16]='';
assert.throws(()=>c.hfAppIssueBuild_(s,{...fresh,orderId:'OTHER'},'now'),/project_mismatch/);assert.throws(()=>c.hfAppIssueBuild_(s,{...fresh,reason:''},'now'),/invalid_reason/);
console.log('PASS issue atomic batch, identity and source preservation, close boolean, stale/formula/conflict guards and owner receipt');
const queue=[['Request','At','Kind','Actor','Payload'],['HF-1','','','owner@test',JSON.stringify({submissionId:'submission-test-0001',raw:'verified input',targetHint:'PROJECT-01'}),'DONE']],normalized=[[],['HF-1-E01','','','verified input','','','','진행','','','','','','','','PROJECT-01','','WRITTEN','','','PROJECT-01','owner@test','HF-1']];
c.hfAppRows_=(ss,name)=>name==='HF_DATA_입력대기열'?queue:name==='HF_DATA_입력정규화'?normalized:[];
assert.equal(c.hfAppReceipt_({}, {submissionId:'submission-test-0001',actor:{email:'owner@test'}}).status,'WRITTEN');assert.equal(c.hfAppReceipt_({}, {requestId:'HF-1',actor:{email:'other@test'}}).status,'NOT_FOUND');
assert.equal(c.hfAppPriorSubmission_({}, {submissionId:'submission-test-0001'},'verified input','owner@test','PROJECT-01').requestId,'HF-1');assert.throws(()=>c.hfAppPriorSubmission_({}, {submissionId:'submission-test-0001'},'changed','owner@test','PROJECT-01'),/request_conflict/);
assert.equal(c.hfAppPriorSubmission_({}, {submissionId:'submission-test-0001'},'verified input','other@test','PROJECT-01'),null);
console.log('PASS server receipt recovery and submission idempotency scoped to personal actor');
