import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const products=[['260601A-039-01','트루메카(대덕전자)','PDM - 1KV - A'],['260601A-039-02','트루메카(대덕전자)','PDM - 1KV - A'],['260710A-052','미코','KDM - 150']];
const c=vm.createContext({Date,Map,Utilities:{formatDate:()=> '2026-09-28',computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()],DigestAlgorithm:{SHA_256:1},Charset:{UTF_8:1}}});
vm.runInContext(fs.readFileSync(new URL('../apps-script/HF_REAL_SAFE_WRITE_V08.gs',import.meta.url),'utf8'),c);
assert.equal(c.workType_('이상준 연차'),'연차');assert.equal(c.workType_('이상준 검수 완료'),'검수');assert.equal(c.workType_('이상준 설비 이상 발생'),'불량발생');
const product={getLastRow:()=>7,getRange:()=>({getDisplayValues:()=>products})};
assert.equal(c.resolveEventProject_(product,'트루메카(대덕전자) PDM - 1KV - A 점검 완료').ambiguous,true);
assert.equal(c.resolveEventProject_(product,'260601A-039-02 트루메카 PDM - 1KV - A 점검').orderId,'260601A-039-02');
assert.equal(c.resolveEventProject_(product,'260601A-039-01 260601A-039-02 점검').ambiguous,true);
assert.equal(c.resolveEventProject_(product,'X260601A-039-02X 점검').ambiguous,true);
assert.equal(c.resolveEventProject_(product,'미코 KDM-150 검수').orderId,'260710A-052');
let saved,headers=['','',''];const sheet={getMaxRows:()=>10,getMaxColumns:()=>23,getSheetId:()=>1907002006,getRange:(r,col,h,w)=>({getDisplayValues:()=>r===1?[headers]:[['']],setValues(v){if(r===1)headers=v[0];else saved=v[0];return this;},setNumberFormat(){}})};
const e={source:'FIELD_INPUT',date:new Date(),receivedAt:new Date(),eventIndex:1,raw:'미코 검수',safe:true,orderId:'260710A-052',actor:'approved@example.com'};
c.appendNorm_({getSheetByName:()=>sheet},e,'HF-test');assert.equal(saved[20],e.orderId);assert.equal(saved[21],e.actor);assert.equal(saved[22],'HF-test');assert.equal(saved[0],'HF-test-E01');assert.equal(saved[3],e.raw);
headers=['unrelated','',''];assert.throws(()=>c.appendNorm_({getSheetByName:()=>sheet},e,'HF-test'),/COLUMN_CONFLICT/);
console.log('PASS Event exact project ID, ambiguous twins, multiple IDs, boundary guard, raw and actor/request audit, schema conflict');
