import assert from 'node:assert/strict';
import {simpleCookie,simplePerson,validateRegistrationKey,bootstrapCookie,hasBootstrap,createRecoveryToken,verifyRecoveryToken} from '../lib/simple-auth.mjs';
const key='test-secret';
assert.equal(validateRegistrationKey(key,key),true);
assert.equal(validateRegistrationKey('wrong',key),false);
const personCookie=simpleCookie({sub:'simple-test',email:'owner@test'},key);
assert.equal(simplePerson({headers:{cookie:personCookie.split(';')[0]}},key).email,'owner@test');
const boot=bootstrapCookie(key);
assert.equal(hasBootstrap({headers:{cookie:boot.split(';')[0]}},key),true);
const token=createRecoveryToken('owner@test','2580',key);
assert.equal(verifyRecoveryToken(token,'2580',key).email,'owner@test');
assert.equal(verifyRecoveryToken(token,'0000',key),null);
console.log('PASS simple-pin bootstrap, signed session and PIN recovery token');
