'use strict';
const BUILD='PC.0.3',content=document.getElementById('content'),detail=document.getElementById('detailDialog'),detailBody=document.getElementById('detailBody');
const state={items:[],projects:[],reports:null,view:'dashboard',connected:false,personal:false,sourceDate:'',lastRead:'',query:'',installPrompt:null,renderRun:0};
let catalogPending=null;
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const norm=value=>String(value||'').toLowerCase().replace(/[\s\-‐‑–—]/g,'');
const isPhone=()=>matchMedia('(max-width:900px)').matches;
async function api(path,body,timeout=35000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(path,{credentials:'include',cache:'no-store',signal:controller.signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let data={};try{data=await response.json();}catch{throw Object.assign(Error('invalid_response'),{status:response.status});}if(!response.ok||data.ok!==true)throw Object.assign(Error(data.error||'request_failed'),{status:response.status,data});return data;}catch(error){if(error.name==='AbortError')throw Object.assign(Error('request_timeout'),{timeout:true});throw error;}finally{clearTimeout(timer);}}
function errorText(error){if(error.timeout)return '서버 응답 시간이 초과됐습니다. 자동 재전송하지 않습니다.';if(error.status===401)return '개인 연결이 필요합니다.';if(error.status===403)return '이 계정 또는 주소의 접근 권한을 확인하세요.';if(error.message==='stale_record')return '다른 변경이 먼저 반영됐습니다. 최신 값을 다시 불러왔습니다.';return '운영DB 응답을 확인하지 못했습니다.';}
function toast(text){const el=$('toast');el.textContent=text;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500);}
function setConnection(ok,text){$('connectionDot').classList.toggle('live',ok);$('connectionTitle').textContent=ok?'운영DB 연결됨':'연결 확인 필요';$('connectionDetail').textContent=text;$('statusBar').textContent=text;$('statusBar').classList.toggle('error',!ok);}
function autoNext(current,next=''){const value=String(current||'').trim();if(/출고완료|납품완료/.test(value))return '완료 · 이력 보관';if(/출고대기|출고 준비/.test(value))return '출고 확인';if(/검수완료/.test(value))return '출고 준비';if(/테스트완료|시운전완료/.test(value))return '검수·출고 판단';if(/갭세팅완료|세팅완료|셋팅완료/.test(value))return '마감조립';if(/조립완료/.test(value))return '검수 준비';if(/자재수령|입고완료/.test(value))return '조립 착수';if(/수정완료/.test(value))return '재조립·테스트';return String(next||'다음 작업 확인').trim();}
function displayItem(item){return {...item,nextAction:autoNext(item.state,item.nextAction)};}
function itemMatches(item,query){return norm([item.orderId,item.customer,item.model,item.state,item.nextAction,item.process,item.cause].join(' ')).includes(norm(query));}
function latest(){return state.items.map(displayItem);}
function statusClass(value){return /출고완료|납품완료/.test(value)?'complete':'';}
function row(item){const x=displayItem(item);return `<tr data-project="${esc(x.orderId)}"><td><span class="status-pill ${statusClass(x.state)}">${esc(x.issueStatus||'OPEN')}</span></td><td><b>${esc(x.orderId)}</b></td><td>${esc(x.customer)}</td><td>${esc(x.model)}</td><td>${esc(x.process||'-')}</td><td><b>${esc(x.state||'미등록')}</b></td><td class="next-action">${esc(x.nextAction)}</td><td>${esc(x.due||'-')}</td></tr>`;}
function projectTable(items,title='프로젝트 현재 흐름',sub='현재상태와 다음 작업을 같은 행에서 확인합니다'){return `<section class="panel"><div class="panel-head"><div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div><input class="search" id="projectSearch" value="${esc(state.query)}" placeholder="발주번호 · 고객 · 장비 · 상태 검색"></div><div class="table-wrap"><table><thead><tr><th>상태</th><th>발주번호</th><th>고객/현장</th><th>모델</th><th>공정</th><th>현재상태</th><th>자동 다음 작업</th><th>납기</th></tr></thead><tbody>${items.map(row).join('')}</tbody></table>${items.length?'':'<div class="empty">조건에 맞는 프로젝트가 없습니다.</div>'}</div></section>`;}
function bindTable(){document.querySelectorAll('[data-project]').forEach(el=>el.onclick=()=>openProject(el.dataset.project));const search=$('projectSearch');if(search)search.oninput=event=>{state.query=event.target.value;render();};}
function dashboard(){const items=latest(),urgent=items.filter(x=>x.priority===1),waiting=items.filter(x=>/대기|보류|지연/.test(x.state)),complete=items.filter(x=>/출고완료|납품완료/.test(x.state)),focus=urgent[0]||items[0];content.innerHTML=`<div class="cards"><article class="kpi"><span>오늘 판단</span><b>${items.length}건</b><small>현재 연결 업무</small></article><article class="kpi"><span>우선 확인</span><b>${urgent.length}건</b><small>납기·공정 영향</small></article><article class="kpi"><span>대기·보류</span><b>${waiting.length}건</b><small>원인 확인 필요</small></article><article class="kpi"><span>완료 표시</span><b>${complete.length}건</b><small>이력 보관</small></article></div><div class="two-col"><section class="panel"><div class="panel-head"><div><h2>결정이 필요한 순서</h2><p>그로우와 HandsFree가 정리한 다음 행동</p></div></div><div class="decision-list">${items.slice(0,6).map(x=>`<article class="decision"><span class="status-pill ${statusClass(x.state)}">${esc(x.state)}</span><div><strong>${esc(x.model)} · ${esc(x.customer)}</strong><small>${esc(x.orderId)} · ${esc(x.process||'공정 미등록')}</small></div><button data-project="${esc(x.orderId)}">${esc(autoNext(x.state,x.nextAction))}</button></article>`).join('')||'<p class="empty">연결된 업무가 없습니다.</p>'}</div></section><aside class="panel"><div class="panel-head"><div><h2>운영 원칙</h2><p>PC 중심 · 모바일 조회</p></div></div><div class="read-card"><h3>${focus?esc(focus.model):'운영DB 연결 확인'}</h3><p>${focus?'현재 '+esc(focus.state)+' · 다음 '+esc(focus.nextAction):'데이터 연결 후 표시합니다.'}</p><p>업무이력 저장과 장비상태 변경은 각각 서버 재조회로 확인합니다.</p><p>일정은 진행내용 입력으로 자동 변경하지 않습니다.</p></div></aside></div>${projectTable(items.slice(0,12),'전체 흐름','행을 누르면 일정·이력·수정 화면이 열립니다')}`;bindTable();}
function projects(){const items=latest().filter(x=>itemMatches(x,state.query));content.innerHTML=projectTable(items,'프로젝트','발주번호·고객·장비·진행내용 통합 검색');bindTable();}
function delivery(){const items=latest().slice().sort((a,b)=>String(a.due||'9999').localeCompare(String(b.due||'9999')));content.innerHTML=projectTable(items,'납기·일정','납기순으로 표시하며 프로젝트를 누르면 자재수령부터 출고까지 확인합니다');bindTable();}
async function history(run){content.innerHTML='<section class="panel"><div class="empty">최근 서버 업무이력을 불러오는 중입니다.</div></section>';try{const projects=state.projects.length?state.projects:await loadCatalog();const targets=projects.slice(0,8),responses=await Promise.allSettled(targets.map(project=>api('/api/sa2-app',{action:'history',orderId:project.orderId})));if(state.view!=='history'||run!==state.renderRun)return;const events=responses.flatMap(result=>result.status==='fulfilled'?(result.value.events||[]):[]).sort((a,b)=>String(b.at||'').localeCompare(String(a.at||''))).slice(0,60);content.innerHTML=`<section class="panel"><div class="panel-head"><div><h2>최근 업무이력</h2><p>원문·작성자·접수번호를 보존한 서버 기록</p></div></div><div class="table-wrap"><table><thead><tr><th>일시</th><th>발주번호</th><th>내용</th><th>작성자</th><th>접수번호</th></tr></thead><tbody>${events.map(e=>`<tr><td>${esc(e.at||'-')}</td><td>${esc(e.orderId||'-')}</td><td>${esc(e.raw||'-')}</td><td>${esc(e.actor||'-')}</td><td>${esc(e.requestId||e.id||'-')}</td></tr>`).join('')}</tbody></table>${events.length?'':'<div class="empty">조회된 업무이력이 없습니다.</div>'}</div></section>`;}catch(error){if(state.view==='history'&&run===state.renderRun)content.innerHTML=`<section class="panel"><div class="empty">${esc(errorText(error))}</div></section>`;}}
function render(){const run=++state.renderRun;document.querySelectorAll('.nav').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view));const titles={dashboard:'오늘 판단',projects:'프로젝트',delivery:'납기·일정',history:'업무이력'};$('pageTitle').textContent=titles[state.view];if(state.view==='dashboard')dashboard();else if(state.view==='projects')projects();else if(state.view==='delivery')delivery();else history(run);}
async function loadCatalog(force=false){if(state.projects.length&&!force)return state.projects;if(catalogPending)return catalogPending;catalogPending=api('/api/sa2-app',{action:'catalog'}).then(data=>{state.projects=Array.isArray(data.projects)?data.projects:[];return state.projects;}).finally(()=>{catalogPending=null;});return catalogPending;}
async function refresh(){setConnection(false,'운영DB 최신값을 다시 읽고 있습니다.');try{const status=await api('/api/sa2-real-status');if(status.live!==true||!Array.isArray(status.currentStatus))throw Error('invalid_response');state.items=status.currentStatus;state.connected=true;state.personal=status.personalConnected===true;state.sourceDate=status.sourceLatestDate||'기준일 미등록';state.lastRead=new Date().toLocaleString('ko-KR');setConnection(true,`${state.items.length}건 · 상태 기준 ${state.sourceDate} · 조회 ${state.lastRead}`);$('userButton').textContent=state.personal?'개인 연결됨':'사용자 연결';render();const warm=()=>loadCatalog(true).catch(()=>{});if('requestIdleCallback'in window)requestIdleCallback(warm,{timeout:1200});else setTimeout(warm,0);return true;}catch(error){state.connected=false;setConnection(false,errorText(error));if(error.status===401)openAuth();content.innerHTML=`<section class="panel"><div class="empty">${esc(errorText(error))}</div></section>`;return false;}}
function modalHead(label,title){return `<div class="modal-head"><div><p class="eyebrow">${esc(label)}</p><h2>${esc(title)}</h2></div><button class="close" data-close>×</button></div>`;}
function closeButtons(){detailBody.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>detail.close());}
function groupPlans(rows){const value=(r,key,index)=>Array.isArray(r)?r[index]:r?.[key],sorted=rows.slice().sort((a,b)=>String(value(a,'date',3)||'').localeCompare(String(value(b,'date',3)||'')));return sorted.map(r=>({date:value(r,'date',3),process:value(r,'process',10)||'공정 미등록',status:value(r,'status',11)||'계획'}));}
async function openProject(orderId){const base=state.items.find(x=>x.orderId===orderId)||state.projects.find(x=>x.orderId===orderId);if(!base)return;detailBody.innerHTML=modalHead('PROJECT',`${base.customer} · ${base.model}`)+'<div class="empty">전체 일정과 이력을 불러오는 중입니다.</div>';if(!detail.open)detail.showModal();closeButtons();try{const [plans,history,issue]=await Promise.all([api('/api/sa2-lifecycle',{action:'plans',orderId}),api('/api/sa2-app',{action:'history',orderId}),base.issueId?api('/api/sa2-app',{action:'issue',issueId:base.issueId}):Promise.resolve(null)]);const current=issue||base,next=autoNext(current.state,current.nextAction),stages=groupPlans(plans.records||plans.plans||[]),events=(history.events||[]).slice().sort((a,b)=>String(b.at||'').localeCompare(String(a.at||''))).slice(0,12);detailBody.innerHTML=modalHead('PROJECT',`${base.customer} · ${base.model}`)+`<div class="detail-meta"><span>${esc(orderId)}</span><span>${esc(base.process||'공정 미등록')}</span><span>납기 ${esc(base.due||'미등록')}</span></div><div class="detail-grid"><div class="detail-box"><small>현재 상태</small><b>${esc(current.state||'미등록')}</b></div><div class="detail-box"><small>다음 작업</small><b>${esc(next)}</b></div></div><h3>전체 조립일정</h3><div class="timeline">${stages.map(s=>`<article><b>${esc(s.process)}</b><span>${esc(s.date)} · ${esc(s.status)}</span></article>`).join('')||'<p>등록된 일정이 없습니다.</p>'}</div><h3>최근 진행내용</h3><div class="timeline">${events.map(e=>`<article><b>${esc(e.raw||'내용 없음')}</b><span>${esc(e.at||'시간 미기록')} · ${esc(e.actor||'입력자 미기록')}</span></article>`).join('')||'<p>입력된 진행내용이 없습니다.</p>'}</div>${issue?editBlock(issue):'<p class="hint">연결된 현재상태 이슈가 없어 업무이력만 조회합니다.</p>'}`;closeButtons();bindEditor(issue);}catch(error){detailBody.innerHTML=modalHead('PROJECT','불러오기 실패')+`<p>${esc(errorText(error))}</p>`;closeButtons();}}
function editBlock(issue){return `<section class="edit-card" data-edit><h3>진행내용 한 번 입력</h3><p class="hint">현재 상황을 입력하면 저장될 상태와 다음 작업을 바로 보여줍니다.</p><textarea id="progressText" placeholder="예: 갭세팅 완료"></textarea><div id="progressPreview" class="preview"><b>현재상태</b> 입력 필요<br><b>다음작업</b> 자동 제안</div><div class="confirm-row"><button class="primary" id="saveButton" disabled>입력한 진행내용 서버 저장</button></div><p id="saveHint" class="hint" role="status" aria-live="polite"></p></section>`;}
function bindEditor(issue){if(!issue||isPhone())return;const text=$('progressText'),preview=$('progressPreview'),button=$('saveButton'),hint=$('saveHint');let proposal=null;const propose=()=>{const current=text.value.trim();proposal=current?{state:current.slice(0,80),nextAction:autoNext(current,issue.nextAction),status:/출고완료|납품완료/.test(current)?'CLOSED':issue.status}:null;preview.innerHTML=proposal?`<b>현재상태</b> ${esc(proposal.state)}<br><b>다음작업</b> ${esc(proposal.nextAction)}<br><b>이슈상태</b> ${esc(proposal.status)}`:'<b>현재상태</b> 입력 필요<br><b>다음작업</b> 자동 제안';button.disabled=!proposal;hint.textContent=proposal?'버튼을 한 번 누르면 서버 저장 후 최신값을 다시 조회합니다.':'진행내용을 입력하세요.';};text.oninput=propose;button.onclick=()=>{if(!proposal){hint.textContent='진행내용을 입력하세요.';return;}saveProgress(issue,proposal,button,hint);};propose();}
async function saveProgress(issue,proposal,button,hint){if(!proposal)return hint.textContent='진행내용을 입력하세요.';if(button.dataset.sending==='true')return;button.dataset.sending='true';button.disabled=true;const requestId=crypto.randomUUID(),raw=`${issue.orderId} · ${issue.customer} · ${issue.model} ${proposal.state}`;hint.textContent='1/3 업무이력을 서버에 저장하고 있습니다…';try{const event=await api('/api/sa2-write',{op:'safe_write',submissionId:requestId,text:raw,targetHint:issue.orderId,source:'DESKTOP',requester:'Emotion'},55000);if(!event.applied){hint.textContent=`서버 접수 ${esc(event.requestId||requestId)} · ${esc(event.status||'확인 필요')}. 자동 재전송하지 않습니다.`;return;}hint.textContent='2/3 업무이력 저장 확인 · 현재상태와 다음작업을 반영하고 있습니다…';const current=await api('/api/sa2-app',{action:'issue',issueId:issue.issueId});const applied=await api('/api/sa2-app',{action:'edit',issueId:issue.issueId,orderId:issue.orderId,expected:current.revision,state:proposal.state,nextAction:proposal.nextAction,status:proposal.status,reason:'PC 진행내용 입력: '+proposal.state,requestId:crypto.randomUUID()},55000);if(applied.status!=='APPLIED')throw Error('unconfirmed');hint.textContent='3/3 서버 최신값을 다시 확인하고 있습니다…';const readback=await api('/api/sa2-app',{action:'issue',issueId:issue.issueId});if(readback.state!==proposal.state||readback.nextAction!==proposal.nextAction)throw Error('readback_mismatch');hint.textContent='업무이력·현재상태·다음작업의 서버 저장과 재조회를 확인했습니다.';toast('저장 후 서버 재조회까지 확인했습니다.');await refresh();setTimeout(()=>openProject(issue.orderId),250);}catch(error){hint.textContent='자동 재전송하지 않았습니다. '+errorText(error);if([400,401,403].includes(error.status)){button.dataset.sending='false';button.disabled=false;}}}
function openAuth(){if(!$('authDialog').open)$('authDialog').showModal();}
async function authSubmit(event){event.preventDefault();const name=$('authName').value.trim(),pin=$('authPin').value.trim();if(!name||!/^[0-9]{4}$/.test(pin)){$('authHint').textContent='이름과 숫자 4자리 PIN을 확인하세요.';return;}$('authHint').textContent='연결 중…';try{await api('/api/sa2-auth',{action:'activate',name,pin});$('authPin').value='';$('authDialog').close();await refresh();}catch(error){$('authHint').textContent=errorText(error);}}
document.querySelectorAll('.nav').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;state.query='';render();});$('refreshButton').onclick=refresh;$('userButton').onclick=openAuth;$('authForm').onsubmit=authSubmit;document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());detail.onclick=event=>{if(event.target===detail)detail.close();};$('authDialog').onclick=event=>{if(event.target===$('authDialog'))$('authDialog').close();};
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();state.installPrompt=event;$('installButton').hidden=false;});$('installButton').onclick=async()=>{if(!state.installPrompt)return;await state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('installButton').hidden=true;};
function applyResponsiveMode(){$('mobileMode').hidden=!isPhone();if(detail.open&&isPhone())detail.querySelectorAll('[data-edit]').forEach(el=>el.remove());}matchMedia('(max-width:900px)').addEventListener('change',applyResponsiveMode);applyResponsiveMode();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});refresh();

